export default {
  useRequestConnection: "useRequestConnection",
  useAcceptConnection: "useAcceptConnection",
  useDeclineConnection: "useDeclineConnection",
  useRemoveConnection: "useRemoveConnection",
  useRemoveConnectionByUserId: "useRemoveConnectionByUserId",
  useFetchConnections: "useFetchConnections",
  useFetchConnectionStatus: "useFetchConnectionStatus",
  useFetchConnectionsCount: "useFetchConnectionsCount",
  useFetchSentPendingConnections: "useFetchSentPendingConnections",
  useFetchReceivedPendingConnections: "useFetchReceivedPendingConnections",
  useFetchConnectionsByUserId: "useFetchConnectionsByUserId",
  useFetchConnectionsCountByUserId: "useFetchConnectionsCountByUserId",
  useConnectionManager: "useConnectionManager",
};